### ISSUE TITLE
[BUG]: dask_cudf.from_cudf super slow

### ISSUE THREAD

**Issue by VibhuJawa** [rapidsai/dask-cudf#150] opened 2019-03-12 22:54 UTC
# dask_cudf.from_cudf super slow

The function dask_cudf.from_cudf is super slow. The time_it output is attached.

I need that function because i do some operations on cudf frame that are not currently supported in dask_cudf .  

```Python
import pandas as pd
import numpy as np
import dask_cudf
import cudf
import time

def get_sample_df(n_rows =1_000,n_keys_id_1 =100,n_keys_id_2 =10,n_keys_id_3 =2,float_col_name='x'):
    
    '''
        Returns  sampled dataframe
    '''
    col_0 = np.random.random(n_rows)
    col_1 = np.random.randint(0, n_keys_id_1, size=n_rows)
    col_2 = np.random.randint(0, n_keys_id_2, size=n_rows)
    col_3 = np.random.randint(0, n_keys_id_3, size=n_rows)
    
    df = pd.DataFrame({float_col_name:col_0,'id_1':col_1,'id_2':col_2,'id_3':col_3})
    return df


def custom_dask_cudf_from_cudf(gdf):
    """
        Returns ddf from gdf
    """
    ts = time.time()
    dtypes = OrderedDict(gdf.dtypes)
    gdf.to_pandas().to_csv('/tmp/temp_test_{}.csv'.format(ts),index=False,header=False,columns =list(dtypes.keys()))
    ddf = dask_cudf.read_csv('/tmp/temp_test_{}.csv'.format(ts),names=list(dtypes.keys()), dtype=list(dtypes.values())) 
    return ddf


df = get_sample_df(n_rows=100_000)
gdf = cudf.from_pandas(df)

%timeit ddf = dask_cudf.from_cudf(gdf,npartitions=1)

%timeit ddf = custom_dask_cudf_from_cudf(gdf)

```

## Dask Time Output
```
44.1 s ± 311 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

## Reading and writing from disk output
```
510 ms ± 33.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

```

**Comment by mrocklin** [comment] 2019-03-13 00:18
Interesting.  Can I suggest the following to help diagnose the issue:

1.  Remove the `LocalCUDACluster` stuff.  I don't think it's necessary to reproduce your issue and it probably complicates things
2.  If you're using `ipython` or `jupyter` then try running the `dask_cudf.from_cudf` function with the `%prun` magic.  This will help you understand which parts of the computation are slow.  This will likely help us identify where the problem is.

**Comment by mrocklin** [comment] 2019-03-13 00:22
Also, sorry to be slow on this.  I need to update my cudf installation, which probably won't happen until sometime tomorrow.

**Comment by VibhuJawa** [comment] 2019-03-13 00:35
## Prun Dump

Thanks for working on this . I removed the local cuda cluster stuff. 

The %prun output is as follows: 

```
       48458628 function calls (48045020 primitive calls) in 54.276 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
   400099    8.413    0.000    9.469    0.000 driver.py:286(safe_cuda_api_call)
   400540    3.386    0.000    3.386    0.000 {method 'reduce' of 'numpy.ufunc' objects}
   400119    3.075    0.000   41.560    0.000 devicearray.py:483(_do_getitem)
   400344    2.130    0.000   13.359    0.000 dummyarray.py:184(__init__)
   400119    1.936    0.000    4.690    0.000 driver.py:1218(view)
   400119    1.891    0.000   17.889    0.000 dummyarray.py:229(__getitem__)
   400119    1.517    0.000   44.355    0.000 devicearray.py:474(__getitem__)
   400005    1.457    0.000   49.888    0.000 buffer.py:129(__getitem__)
   400119    1.334    0.000    1.863    0.000 dummyarray.py:55(__getitem__)
   400540    1.243    0.000    5.015    0.000 fromnumeric.py:64(_wrapreduction)
2403527/2003317    1.223    0.000    1.443    0.000 {built-in method builtins.getattr}
   400344    1.187    0.000    3.686    0.000 dummyarray.py:218(_compute_extent)
4848826/4848820    1.145    0.000    1.859    0.000 {built-in method builtins.isinstance}
   400344    1.087    0.000    1.717    0.000 dummyarray.py:194(_compute_layout)
   400002    1.081    0.000    1.081    0.000 {method 'view' of 'numpy.generic' objects}
   400000    1.007    0.000   53.150    0.000 series.py:217(__getitem__)
   400187    0.990    0.000    1.067    0.000 utils.py:618(__init__)
   400012    0.918    0.000   14.786    0.000 driver.py:1834(device_to_host)
   400119    0.890    0.000    1.956    0.000 driver.py:1305(__init__)
   400046    0.850    0.000    0.850    0.000 {built-in method numpy.core.multiarray.empty}
   400025    0.813    0.000    2.306    0.000 driver.py:1738(host_pointer)
   400177    0.743    0.000    1.288    0.000 utils.py:636(__call__)
   400002    0.735    0.000   50.870    0.000 column.py:370(element_indexing)
       12    0.721    0.060   54.023    4.502 series.py:1409(__getitem__)
   800688    0.654    0.000    1.817    0.000 dummyarray.py:134(compute_index)
   400025    0.605    0.000    0.605    0.000 {built-in method numba.mviewbuf.memoryview_get_buffer}
   400270    0.514    0.000    1.626    0.000 devices.py:154(get_or_create_context)
   400540    0.509    0.000    5.525    0.000 fromnumeric.py:2478(prod)
  1601372    0.478    0.000    0.706    0.000 dummyarray.py:135(<genexpr>)
   800688    0.458    0.000    1.163    0.000 {built-in method builtins.sum}
   400071    0.450    0.000    1.861    0.000 driver.py:1780(device_ctypes_pointer)
   800050    0.442    0.000    0.579    0.000 driver.py:1722(_is_datetime_dtype)
400148/400090    0.438    0.000   46.699    0.000 devices.py:209(_require_cuda_context)
   400118    0.413    0.000    0.413    0.000 driver.py:1316(deref)
   402560    0.390    0.000    0.714    0.000 abc.py:180(__instancecheck__)
   400188    0.379    0.000    0.380    0.000 driver.py:1180(__init__)
   400119    0.351    0.000    2.213    0.000 dummyarray.py:244(<listcomp>)
   400099    0.341    0.000    0.589    0.000 __init__.py:1543(isEnabledFor)
   404341    0.324    0.000    0.324    0.000 _weakrefset.py:70(__contains__)
   800684    0.297    0.000    0.424    0.000 dummyarray.py:206(is_contig)
   800589    0.294    0.000    0.294    0.000 {built-in method builtins.max}
   400002    0.290    0.000    0.451    0.000 utils.py:78(normalize_index)
   400270    0.276    0.000    1.902    0.000 devices.py:190(get_context)
   800540    0.269    0.000    0.269    0.000 threadlocal.py:13(stack)
   400099    0.262    0.000    0.851    0.000 __init__.py:1285(debug)
   800216    0.256    0.000    0.612    0.000 driver.py:1329(__getattr__)
   400342    0.251    0.000    0.251    0.000 dummyarray.py:45(__init__)
   400099    0.248    0.000    0.248    0.000 __init__.py:1529(getEffectiveLevel)
   800199    0.246    0.000    0.246    0.000 {built-in method builtins.min}
  1200356    0.242    0.000    0.242    0.000 driver.py:1193(owner)
2006842/2006673    0.241    0.000    0.242    0.000 {built-in method builtins.len}
   400071    0.236    0.000    2.096    0.000 driver.py:1775(device_pointer)
   800684    0.227    0.000    0.227    0.000 dummyarray.py:106(get_offset)
   400270    0.215    0.000    0.494    0.000 devices.py:107(current_context)
   400270    0.212    0.000    0.411    0.000 threadlocal.py:33(is_empty)
   400270    0.209    0.000    0.279    0.000 threadlocal.py:29(top)
   400270    0.206    0.000    0.618    0.000 threadlocal.py:37(__bool__)
   400099    0.205    0.000    0.205    0.000 driver.py:314(_check_error)
1203023/1202843    0.204    0.000    0.208    0.000 {built-in method builtins.next}
   400071    0.199    0.000    1.050    0.000 driver.py:1799(require_device_memory)
   400559    0.189    0.000    0.189    0.000 {built-in method __new__ of type object at 0x561abf0dfd60}
   800686    0.163    0.000    0.163    0.000 dummyarray.py:187(<genexpr>)
   400032    0.156    0.000    0.156    0.000 column.py:293(has_null_mask)
        4    0.151    0.038    0.152    0.038 nvvm.py:166(compile)
   400344    0.147    0.000    0.147    0.000 dummyarray.py:220(<listcomp>)
   400025    0.137    0.000    0.308    0.000 driver.py:1729(_workaround_for_datetime)
   800684    0.135    0.000    0.135    0.000 dummyarray.py:130(is_contiguous)
   400844    0.122    0.000    0.122    0.000 {method 'pop' of 'dict' objects}
   400012    0.121    0.000    0.121    0.000 dummyarray.py:141(__init__)
   400391    0.118    0.000    0.851    0.000 driver.py:1788(is_device_memory)
   400143    0.109    0.000    0.109    0.000 {built-in method _weakref.proxy}
   800024    0.108    0.000    0.108    0.000 dummyarray.py:144(iter_contiguous_extent)
   400169    0.104    0.000    0.104    0.000 devicearray.py:149(_default_stream)
   800686    0.101    0.000    0.101    0.000 dummyarray.py:188(<genexpr>)
   400119    0.101    0.000    0.101    0.000 dummyarray.py:245(<listcomp>)
```

**Comment by randerzander** [comment] 2019-03-13 15:45
I'm also seeing very slow performance of `from_cudf`.

I use npartitions=1, which is not ideal, but I wouldn't expect it to be this slow for such a small number of rows.

Test:
```
import cudf, dask_cudf
import time

nelem=1

for x in range(1, 6):
    nelem = nelem * 10
    df = cudf.DataFrame()
    df['id'] = range(0, nelem)
    df['text'] = ['blah']*nelem
    t0 = time.time()
    ddf = dask_cudf.from_cudf(df, npartitions=1)
    t1 = time.time()
    print(f'{nelem}: {round(t1-t0)}s')
```
```
10: 0s
100: 0s
1000: 1s
10000: 8s
100000: 82s
```

**Comment by quasiben** [comment] 2019-03-13 16:06
I can take a look at this after lunch today

**Comment by mrocklin** [comment] 2019-03-13 16:13
I'm looking at it now

**Comment by mrocklin** [comment] 2019-03-13 16:18
Here is the problem, cudf's `iloc` is slow:

```python
In [1]: import cudf, dask.dataframe as dd, numpy as np

In [2]: df = cudf.DataFrame({'x': np.arange(100000)})

In [3]: %time df.iloc[1000:100000]
CPU times: user 10.3 s, sys: 136 ms, total: 10.5 s
Wall time: 10.5 s
Out[3]: <cudf.DataFrame ncols=1 nrows=99000 >
```

I'll raise upstream and close this.

**Comment by mrocklin** [comment] 2019-03-13 16:19
See https://github.com/rapidsai/cudf/issues/1176

**Comment by randerzander** [comment] 2019-03-20 21:22
I believe this was resolved. Please re-open if the issue resurfaces

**Closed by randerzander** 2019-03-20 21:22 UTC
